import type { Category, Subcategory } from '@raadi/catalog';
import {
  Armchair,
  Baby,
  BedDouble,
  Bike,
  Briefcase,
  Building2,
  Car,
  CarFront,
  Caravan,
  Dog,
  Factory,
  GraduationCap,
  Guitar,
  HardHat,
  House,
  KeyRound,
  LandPlot,
  Laptop,
  Luggage,
  Motorbike,
  Palette,
  Plane,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Shovel,
  Smartphone,
  Stethoscope,
  Tent,
  TreePine,
  Truck,
  UtensilsCrossed,
  Wrench,
  type LucideIcon,
} from 'lucide-react';

export const CATEGORY_ICONS: Record<Category, LucideIcon> = {
  torget: ShoppingBag,
  bil: Car,
  eiendom: House,
  jobb: Briefcase,
  reise: Plane,
};

export const SUBCATEGORY_ICONS: Record<Subcategory, LucideIcon> = {
  elektronikk: Smartphone,
  mobler: Armchair,
  klaer: Shirt,
  sport: Bike,
  barn: Baby,
  hobby: Guitar,
  hage: Shovel,
  antikviteter: Palette,
  dyr: Dog,
  kjoretoyutstyr: Wrench,
  personbil: CarFront,
  varebil: Truck,
  motorsykkel: Motorbike,
  bobil: Caravan,
  salg: KeyRound,
  utleie: House,
  fritid: TreePine,
  tomt: LandPlot,
  nybygg: HardHat,
  naering: Building2,
  it: Laptop,
  helse: Stethoscope,
  bygg: HardHat,
  undervisning: GraduationCap,
  handel: ShoppingCart,
  transport: Truck,
  kontor: Briefcase,
  industri: Factory,
  reiseliv: UtensilsCrossed,
  hytteutleie: Tent,
  leilighet: BedDouble,
  pakkereise: Luggage,
};

/** Shortcuts on a category page: a label key under `categoryPage.shortcuts` and the filters it sets. */
export const SHORTCUTS: Record<Category, Array<{ key: string; params: Record<string, string> }>> = {
  torget: [
    { key: 'new', params: { condition: 'new' } },
    { key: 'under500', params: { priceMax: '500' } },
    { key: 'furniture', params: { subcategory: 'mobler' } },
  ],
  bil: [
    { key: 'electric', params: { subcategory: 'personbil', fuel: 'electric' } },
    { key: 'automatic', params: { subcategory: 'personbil', gearbox: 'automatic' } },
    { key: 'awd', params: { subcategory: 'personbil', drivetrain: 'awd' } },
    {
      key: 'recent',
      params: { subcategory: 'personbil', yearMin: String(new Date().getFullYear() - 3) },
    },
    { key: 'lowMileage', params: { subcategory: 'personbil', mileageMax: '50000' } },
  ],
  eiendom: [
    { key: 'apartments', params: { subcategory: 'salg', propertyType: 'apartment' } },
    { key: 'houses', params: { subcategory: 'salg', propertyType: 'house' } },
    { key: 'threeBedrooms', params: { subcategory: 'salg', bedroomsMin: '3' } },
    { key: 'freehold', params: { subcategory: 'salg', ownership: 'freehold' } },
  ],
  jobb: [
    { key: 'fullTime', params: { employmentType: 'full_time' } },
    { key: 'partTime', params: { employmentType: 'part_time' } },
    { key: 'internship', params: { employmentType: 'internship' } },
  ],
  reise: [
    { key: 'bigGroups', params: { guestsMin: '6' } },
    { key: 'cabins', params: { subcategory: 'hytteutleie' } },
  ],
};
